# Generated by Django 5.0.4 on 2024-04-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_products_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='owner',
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='myapp.users'),
        ),
    ]
